name: Publish Github Page

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build
        mv dist/browser docs
    
    - name: Test Coverage
      run: |
        npm run test:coverage
        mv coverage/lcov-report docs/coverage

    - name: Setup Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Publish to gh-pages
      run: |
        git checkout --orphan gh-pages
        git reset --hard
        git add -f docs/*
        git commit -m "Publish"
        git push -f origin gh-pages:gh-pages
