name: Publish Github Page

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - name: Publish
      run: |
        git checkout --orphan gh-pages
        git reset --hard
        git add -f dist/*
        git commit -m "Publish"
        git push -f origin gh-pages:gh-pages
